### ISSUE TITLE
[Suggestion] Fire event on skill requirement checks

### ISSUE THREAD

**Issue by thebrightspark** [Coders-After-Dark/Reskillable#138]
So I'm looking into creating a mod that adds the ability use the functionality of teams in Reskillable so that players within teams can "share" the skills they have. That'd mean, for example, that a player with Mining lvl 1 would be able to do things that are locked behind Mining lvl 16 if there is a player in their team with Mining lvl 16+ already.

However currently I can't see any way to do this easily. I am suggesting for an event to be created which is fired every time a skill requirement is checked so that it can be intercepted for other uses (like mine: checking other players' skills) and forcefully set to either succeed, fail, or pass and do normal logic.

**Comment by Lanse505** [comment]
I think there is already a mod like this by Buuz.

Cant remember the name atm.
Although an event like that could probably be added, i'd refer this to Pupnewfster since he's the internals guru.

**Comment by thebrightspark** [comment]
Ah this one?
https://minecraft.curseforge.com/projects/together-forever

Would that work with players' skills?

**Comment by thebrightspark** [comment]
Just noticed it has some Reskillable specific actions, so I think it will 😄 
Regardless, I think this event suggestion would be a good idea which will open up Reskillable for more addons.

**Comment by pupnewfster** [comment]
While this does seem like an interesting concept, I think it is probably not worthwhile to do.

1. Some of events we listen to get thrown/used a lot which is one reason I implemented Requirement Caching. For example, until a player changes their skill level, it doesn't need to recheck if they have mining 3 each time something asks. This is more useful with some of the more complex requirements such as some in CompatSkills. This would probably be a relatively big performance hit of throwing an event and waiting to see if something external says that a Requirement is met or not.
2. If an event was fired when requirements are being checked and then in the event people checked if someone else had certain requirements, that would just throw a chain of events when looking if people have things.

3. This actually is possible (though in a more limited sense) for addons to do currently. If you create custom Requirements and set them to not be cacheable, then in the achievedByPlayer method you add your logic that checks the normal logic AND checks their teammates then you would be able to have what you want accomplished of the people of different levels on the same team being able to do things. (If you have more questions about wanting to implement something like this I can probably answer them, you may even be able to do it by implementing OuterRequirement and making a requirement that can handle all other types of requirements instead of just making a skill specific one.

4. Finally in the next major version I have been planning on adding more native support for teams, that instead of using something like Together Forever, Reskillable will be able to handle it all. This way I also would be able to add support for Fake Players "leveling up" with a player.

**Comment by thebrightspark** [comment]
Ah I see, fair enough.
To be honest though, your second point shouldn't be something for you to worry about as that's on the developer of the addon, but I understand the concern.
I may try have a go at what you mentioned then in point 3 for now, but of course having teams built into Reskillable would be best and I look forward to when you manage to implement that 😄

**Comment by Lanse505** [comment]
@thebrightspark 
Can this issue be closed?

**Comment by thebrightspark** [comment]
Yes
