### ISSUE TITLE
Nature's Aura

### ISSUE THREAD

**Issue by O13SC3N3** [Coders-After-Dark/Reskillable#151]
https://github.com/Ellpeck/NaturesAura/issues/29

Seems to be an issue going on with the Advancements.

Original Error: https://paste.dimdev.org/igukayujax.mccrash

**Comment by pupnewfster** [comment]
I am unable to reproduce this with Nature's Aura and Reskillable. I think some other mod you have probably has invalid advancements that are being loaded by Reskillable. And that Patchouli is finding that they are invalid. From what I can tell though Patchouli has added handling for if an Advancement is null so I think this issue is fixed. Given I believe one of your mods is just shipping invalid advancements.
