### ISSUE TITLE
Incompatibility with Chococraft.

### ISSUE THREAD

**Issue by SlayerTheChikken** [Coders-After-Dark/Reskillable#152]
https://github.com/Slayer5934/ChocoCraft3SLY/issues/27

Not sure who is to blame :P

**Comment by pupnewfster** [comment]
I will look into it a bit later, but has this been tested with the latest version of reskillable? The crash report has version 1.10.0, and the latest version is [1.12.5](https://github.com/Coders-After-Dark/Reskillable/blob/develop/1.12.2/CHANGELOG.MD#1125). I don't think anything has changed about the right clicking block code since then, but I could be wrong. (The line numbers at the very least might have changed.

**Comment by pupnewfster** [comment]
Ok I have some theories as to what may be causing it. I think on reskillable's end it is this [line](https://github.com/Coders-After-Dark/Reskillable/blob/develop/1.12.2/src/main/java/codersafterdark/reskillable/base/LevelLockHandler.java#L334) not the one linked in the crash report (due to the older version). And then  for chococraft it goes to this [line](https://github.com/Slayer5934/ChocoCraft3SLY/blob/master/src/main/java/net/slayer5934/chococraft/common/tileentities/TileEntityChocoboEgg.java#L24) Given what could be throwing a null pointer at that point, my guess is that `breedInfo` is somehow null, so that calling serialize is throwing a null pointer. Given I see you are the dev of that, could you do a check when you get a chance to see if it still crashes if you add a an if statement around the setTag of
```java
if (this.breedInfo != null) {
nbt.setTag(NBTKEY_BREEDINFO, this.breedInfo.serialize());
}
```
and see if it still crashes. (I mainly don't feel like having to create a local branch of Chococraft given it isn't just an end user reporting it.)

**Comment by SlayerTheChikken** [comment]
I'm testing this fix right now, I also added the check in a few other places to be sure.
Edit: Seems to be fixed, I'll do some more testing to make sure, and then report back here. If everything is A OK then you can close the issue if you want.

**Comment by SlayerTheChikken** [comment]
Should be solved now https://github.com/Slayer5934/ChocoCraft3SLY/commit/ab005fb23b156dcf2fa4b47fde6aef07c7a470d2
No negative consequences during testing.
