### ISSUE TITLE
Skills randomly resetting

### ISSUE THREAD

**Issue by TomasTobrman** [Coders-After-Dark/Reskillable#164]
I want to level up something but when I do and reopen the window, all skills are reset to 1

**Comment by davidixxx** [comment]
Me too...
![image](https://user-images.githubusercontent.com/55401621/64972618-fa1a8900-d87f-11e9-8226-3e32fba92428.png)
and crashes https://paste.dimdev.org/elepetunil.mccrash

**Comment by Skop12** [comment]
I've had the same issue.  

sometimes with a crash https://paste.dimdev.org/cedofesaci.mccrash

EDIT: 
ok, I think i fixed the resetting (not 100% sure). I noticed that davidixxx had VanillaFix aswell and no one else with my modpack was having problems so I thought maybe it was the problem.
I set the "Optimizations and vanilla bug fixes" to false in Mod Options (for VanillaFix) and havent had skills reset since.

**Comment by TomasTobrman** [comment]
@Skop12 Thank you! This actually worked for me, too 😁

**Comment by ghost** [comment]
I'm having the same issue where whenever I go to play RLCraft and I want to use my levels on something, I do and then when I come back and open up the skills menu all of my skills are reset to 1!

Please fix this issue, it's a huge problem for anyone playing RLCraft.

**Comment by ghost** [comment]
> I've had the same issue.
> 
> sometimes with a crash https://paste.dimdev.org/cedofesaci.mccrash
> 
> EDIT:
> ok, I think i fixed the resetting (not 100% sure). I noticed that davidixxx had VanillaFix aswell and no one else with my modpack was having problems so I thought maybe it was the problem.
> I set the "Optimizations and vanilla bug fixes" to false in Mod Options (for VanillaFix) and havent had skills reset since.

Ok ill try it out because I installed VanillaFix too.

**Comment by pupnewfster** [comment]
This is due to VanillaFix, if you want it fixed, either change the config option for vanilla fix yourself, to disable the vanilla optimizations, REPORT the issue to VanillaFix as I am not sure anyone has bothered doing that yet, OR open a bug report in RLCraft requesting that they change the default config they ship for vanilla fix to having the option disabled. (Assuming you didn't manually add VanillaFix, if you did don't bother the RLCraft devs about it)
