### ISSUE TITLE
Reskillable+CompatSkill+ExtraSkill+Gamestages???

### ISSUE THREAD

**Issue by TheSexyYeti** [Coders-After-Dark/Reskillable#171]
Can Reskillable be used in combination with CompatSkill, ExtraSkills and gamestages to create weighted loot value. I wanna use ExtraSkills to add a Treasure Hunter or Luck skill. That the higher your level in this skill, the better loot you might get from a chest of mob drop.

On a side note. You should make Reskillable fully customizable for modpack creators. Allowing them to add/remove skills and/or traits. Even the default one. Obviously this would require the modpack creator to have some basic coding knowledge. Which from my experience of working on my own. Building a modpack require some kind of knowledge of basic coding.

**Comment by pupnewfster** [comment]
I would highly recommend using CompatSkills over ExtraSkills, as it is by us and has more capabilities of what it can do/customization of a custom skill. Not only can it create custom skills but it can create custom traits and integrate with gamestages. In terms of making it so that you change the loot based on your skill level, this *is* possible by using the integration Reskillable has for loot tables and then using something like loottweaker to set different drops based on the requirements the player has.

https://github.com/pupnewfster/GGSkyblock/tree/master/scripts/loot is an example of making mobs drop ores based on levels.

If you have more questions about how to accomplish things you can join our [discord](https://discord.gg/Q2k3uEe) and ask.
