### ISSUE TITLE
Bountiful Baubles Compatibility

### ISSUE THREAD

**Issue by TricksterCoyote** [Coders-After-Dark/Reskillable#178]
I've noticed recently that the level requirements for many items in the mod Bountiful Baubles are completely outrageous and unattainable. For example, the Lucky Horseshoe requires a magic skill of 999, while the level cap is 32. Is there a way to change the maximum level requirements of items so that they can't ask for more than is possible to give? Or is there another way to level up skills past 32 that I've missed somehow?

**Comment by pupnewfster** [comment]
Take this up with whoever made the pack that you are playing. Reskillable only locks a few ***vanilla*** items in the default configuration, but gives pack creators the ability to lock various items. I also recommend that you mention to the pack dev if they want to "lock" an item in a way that cannot ever be met to instead just use `unobtainable` as the requirement instead of setting a level to 999
