### ISSUE TITLE
Modifications from Skillable and download link to the JAR file

### ISSUE THREAD

**Issue by Fireztonez** [Coders-After-Dark/Reskillable#31]
Hello,
 I have now Skillable in my pack in developpment and I want to know what is the change you make in your "Reskillable mod", from the original Skillable mod and if is it possible to give a Downlaod link for the jar file.

Thank's,
Fireztonez

**Comment by Lanse505** [comment]
1) This is the current changelog
`
Reskillable Changelog
Version: Reskillable-1.12.2-1.0.0

General:
- Removed reliance on AutoRegLib

Non-Modders:
Additions:
- Added Crafttweaker Support for Requirement Locking
- Added support for individual Skill level max values.
- Added a scrolling feature to the Skill Info GUI to help facilitate.
- Added NBT Support for Requirement Locking.

Fixes:
- Fixed Vazkii#18 - Implementing a fix for the Perfect Recovery Trait
- Fixed Vazkii#20 and Vazkii#5 making it so Reskillable now works on Servers.
- Implemented a potential fix for Reskillable#14 - Tools that can break multiple blocks should now not be able to cheese Reskillable.
- Implemented an improved behaviour to the level-up button to make it more obvious where to click to invest xp for points.
	- Fixes Reskillable#11

Modders:
- Added support to add new Skills to Reskillable.
- Added the ability to add traits to already existing Skills.
- Implemented it so Skill Icons are now part of the Skill Constructor instead of assumed to be part of the GUI.
- Implemented it so the Skill Constructor now takes a resource location for the background texture for the Skill Info GUI instead of a Block instance.
`

**Comment by Lanse505** [comment]
2) We are not handing out the Jar atm since the mod is still under reworking.
Once we feel it's in a state to be released, it'll be found on CurseForge!

**Comment by Fireztonez** [comment]
Thank's for the reply, I will wait to see your mod! I hope is will be available soon, but I can wait!!
