### ISSUE TITLE
[Bug]: Disabling skills does nothing

### ISSUE THREAD

**Issue by Sixdd6** [Coders-After-Dark/Reskillable#56]
Basically what the title says, setting any skill to `B:Enabled=false` in the config does not disable the skill from appearing. Removing the traits seems to work well so far. I'd like to be able to remove all default skills and traits and replace them with my own custom ones. If any other info is needed I'd be happy to oblige.

EDIT: After disabling all traits the "Sidestep" trait is still showing under Agility.

MC 1.12.2
Forge 14.23.2.2653
Reskillable 1.0.0

**Comment by Lanse505** [comment]
Will test and look into once I get home.

**Comment by Sixdd6** [comment]
Thank you 😃

**Comment by Lanse505** [comment]
I've looked into it, and it's gonna require some tinkering.
Not sure how long it might take sorry :(

In the mean time, can I offer you a new release of both Reskillable and CompatSkills with lots of new goodness ;)

https://minecraft.curseforge.com/projects/reskillable/files/2550842
https://minecraft.curseforge.com/projects/compatskills/files/2550844

**Comment by Sixdd6** [comment]
I'll always take new features 😄 
I can always temporarily repurpose the default skills while I wait for a fix.

**Comment by Sixdd6** [comment]
did this not make it to the 1.2.0 release?

**Comment by Lanse505** [comment]
Unfortunately not, it proved to be a bigger issue than originally anticipated with crash issues due to parents checks here and there. I'm hoping for 1.3.0 however I won't be able to look into it until after this weekend since I'm not at home currently.

I was/am thinking about suggesting this as a secondary PR target for @pupnewfster 's next PR if he want's to do it.
