### ISSUE TITLE
No config or mod description

### ISSUE THREAD

**Issue by Nianor** [Coders-After-Dark/Reskillable#69]
![2018-04-22_18 05 06](https://user-images.githubusercontent.com/11527859/39102407-67efe4b8-4658-11e8-8b0f-a66804555671.png)
The game has no keybinds related to Reskillable, and despite the presence of a mcmod.info file, the game acts as if none is present. The issue occurs with Reskillable 1.2.0 and 1.2.1.

No idea if this is related, but I also threw this error when attempting to launch the game with CompatSkills.
[crash-2018-04-22_13.47.36-client.txt](https://github.com/Coders-After-Dark/Reskillable/files/1936324/crash-2018-04-22_13.47.36-client.txt)

**Comment by Lanse505** [comment]
We do not currently have an in-game mod config.
The config is still generated in the config directory.

I'll work on adding a mcmod.info mod with a short description of the mod.
However, until then most of the information should exist in the config or on our CurseForge Page.

**Comment by Nianor** [comment]
I couldn't find how to open the skill GUI in the config or on the CurseForge, which was what prompted all of this. It's not an option in the config, and there's no keybind menu that I can find, so I suspect that whatever the default key is, it's in conflict with something, but I can't find any way to resolve that conflict.

**Comment by Lanse505** [comment]
Open your inventory, there is a tab on the left side with a Reskillable Icon.
Click on that and you'll gain access to the Reskillable GUI.

I'm gonna work on adding a mcmod.info to the mod.

In-game configs are something we've discussed but it isn't super straightforward to implement.
We'll look into it but no ETA.

**Comment by Lanse505** [comment]
Mod Description has been added in-game now:
https://i.imgur.com/CX5FFB1.png

We do not currently have a Keybind 🤔 
I wonder @SkySom What do you think about adding a Keybind of the GUI as well?
I'm fine with the current approach but some people might not like it.

**Comment by Nianor** [comment]
The problem with not having an alternate means to open the GUI is that it can conflict with other mods that edit the inventory, as I suspect was the case on my end.

**Comment by Nianor** [comment]
I’m on my phone right now, but I’ll give it a test once I’m home just to be sure.

**Comment by Nianor** [comment]
Yeah, it looks like it was conflicting with The Camping Mod, which looks like it overwrites the base GUI.

**Comment by Lanse505** [comment]
As it currently stands this is an issue with "The Camping Mod".
He is replacing the entire inventory which not only breaks compat with Reskillable but with any mod that adds tabs-style content to the inventory, for example, Baubles.

I'm gonna look into adding a keybind-option and put it on the todo list for Reskillable 1.3.0.
However, this is **not** a reskillable issue but rather an issue that occurs due to his mod breaking compat with anything that relies on the vanilla inventory!

My recommendation outside of waiting for me to implement the keybind is to make an issue post on his issue tracker asking him to add Reskillable Compat similarly to https://github.com/Rikmuld/MC-Camping/issues/101.

However, we will not be adding compat for his mod since it's him breaking shit >.>

I'm going to be closing this issue and opening up a separate new post for the Keybind feature.

**Comment by adrwa** [comment]
ree
